### ISSUE TITLE
add the fyydiverse

### ISSUE THREAD

**Issue by ghost** [c0c0bird/chaos-world#4]
Hiho everybody!

Would you please add the fyydiverse to the map?

It's located at https://fyyd.de/fyydiverse/fyyd.json with the binary kitchen as the most commonly used instance atm.
Text could be "the fyydiverse" and the logo can be found at https://fyyd.de/images/wa/fyyd-logos-chaos-world.png with 32px and 64px height each.

Thanks. I'm going to build the exit to the map in a minute :)

**Comment by c0c0bird** [comment]
Thanks! You are linked on the island in the northern sea.
Please use this exit URL: /_/global/c0c0bird.github.io/chaos-world/main.json#start_nordsee_unten
