### ISSUE TITLE
Adding Erfindergarden to the chaos world map

### ISSUE THREAD

**Issue by ARKopp** [c0c0bird/chaos-world#5]
Hallo can you add Erfindergarden to the map. 

We are a Maker Hacker Community in Munich. 

This is our map https://play.wa.binary-kitchen.de/_/global/erfindergarden.github.io/workadventure-map-erfindergarden/main.json

you can find our logo here https://erfindergarden.de/presse/

thank you for adding!

**Comment by c0c0bird** [comment]
Thank you! An exit to Erfindergarden is now placed in Munich, next to the Maker Lab.
