### ISSUE TITLE
Adding Hacklabor to the Chaos Communication Continent

### ISSUE THREAD

**Issue by n0ctua** [c0c0bird/chaos-world#7]
Hi there,

thanks for your great work! 

Could you please add an exit for **_Hacklabor_**, the Hackspace and Chaostreff in Schwerin, to the chaos world?

The link to our online world: https://play.workadventu.re/_/global/hacklabor.gitlab.io/online_world/main.json
You can find the logo here: https://hacklabor.de/assets/img/logo/Logo_medium_black.svg.png

Thank you in advance!

**Comment by c0c0bird** [comment]
Hi,

thank you! I added Hacklabor to the map.

See you in the world
coco

**Comment by n0ctua** [comment]
Awesome! Thanks a lot!
